### ISSUE TITLE
проверить ДЗ

### ISSUE THREAD

**Issue by Nikrom13** [Nikrom13/Name-Service#1]
Не уверен что выбрал правильный путь реализации задачи, но тем не менее, все работает.
Проверьте пожалуйста код в ,travis.yml
Интересует строчка с покрытием, не собирается на сайте codcov, но в трависи он добавлен. Так же репозиторий сразу не показывался пришлось в ручную заходить.

**Comment by Nikrom13** [comment]
Нашел ошибку, она оказалась критичной, после исправления вcе заработало.
https://github.com/Nikrom13/Name-Service/blob/2701ff145c6e6fdd7289c7291b14845aaad95173/.travis.yml#L7    пробел между "-""bash"

**Comment by Nikrom13** [comment]
поправил код в тестах 88a50f3c57193985fb2f1fd2b36c07d7fd4b59a2

**Comment by coursar** [comment]
всё ок
